# =============================================
# TEACHER BOT — TILLAR FAYLI
# =============================================

# Barcha qo'llab-quvvatlanadigan tillar
LANGUAGES = {
    "🇺🇿 O'zbek":   "uz",
    "🇷🇺 Русский":  "ru",
    "🇬🇧 English":  "en",
    "🇩🇪 Deutsch":  "de",
    "🇫🇷 Français": "fr",
    "🇪🇸 Español":  "es",
    "🇹🇷 Türkçe":   "tr",
    "🇸🇦 العربية":  "ar",
    "🇨🇳 中文":      "zh",
    "🇯🇵 日本語":    "ja",
    "🇰🇷 한국어":    "ko",
    "🇮🇳 Hindi":    "hi",
}

# Har bir tildagi matnlar
TEXTS = {
    "uz": {
        "welcome":         "👋 Xush kelibsiz!\n\n🌍 Tilni tanlang:",
        "soha":            "✅ Til tanlandi!\n\n📂 Soha tanlang:",
        "fan":             "📚 Fan tanlang:",
        "choose_topic":    "📌 Mavzuni tanlang:",
        "daraja":          "📊 Darajangizni tanlang:",
        "maqsad":          "🎯 Maqsadingiz nima?",
        "vaqt":            "⏰ Kuniga qancha vaqt ajrata olasiz?",
        "loading":         "🤖 AI dars tayyorlamoqda...",
        "test_loading":    "🤖 Test tayyorlanmoqda...",
        "test_result":     "📊 Test natijasiga qarab darajangizni tanlang:",
        "understood":      "✅ Tushundim",
        "not_understood":  "❓ Tushunmadim",
        "ask":             "💬 Savol berish",
        "home":            "🏠 Bosh sahifa",
        "pro":             "🏆 Professional bo'lish",
        "job":             "💼 Ish topish",
        "learn":           "📚 Bilim olish",
        "project":         "🚀 Loyiha yaratish",
        "ask_prompt":      "✍️ Savolingizni yozing 👇",
        "lesson_done":     "🎉 Ajoyib! Darsni tugatdingiz!\n\n⭐ {kun}-kun darsi bajarildi!",
        "next_lesson":     "➡️ {kun}-kun darsiga o'tish 🔓",
        "next_post":       "➡️ Keyingi post",
        "next_day_locked": "🔒 Keyingi dars 12 soatdan keyin ochiladi",
        "post_note":       "Bu {current_post}/{total_posts} post. Har bir post uchun bitta rasm yoki diagramma yordamida tushuntiring.",
        "post_understood": "✅ Ushbu bo'limni tushundim. Davom etish uchun keyingi postga o'ting.",
        "choose_topic":    "📂 Iltimos, dasturlash yo'nalishini tanlang:",
        "daraja_unknown":  "🤔 Darajamni bilmayman — test olaman",
        "lang_name":       "O'zbek",
        "test_prompt":     "'{fan}' mavzusi bo'yicha o'quvchi darajasini aniqlash uchun 5 ta savol yozing (A B C D). Javob {lang_name} tilida yozing.",
        "answer_prompt":   "{fan} mavzusi bo'yicha savol: {question}. {lang_name} tilida tushuntirish yozing.",
        "lesson_template": "Siz {lang_name} tilida dars yozing.\n\nO'quvchi:\n- Fani: {fan}\n- Darajasi: {daraja}\n- Maqsadi: {maqsad}\n- Kunlik vaqti: {vaqt}\n{extra}\n\nQuyidagi FORMAT-DA yozing:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 {kun}-kun\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Bugungi mavzu: [MAVZU]\n\n[Qisqacha kirish]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 ASOSIY TUSHUNCHA\n━━━━━━━━━━━━━━━━━━━━\n[Tushuntirish]\n\n🔍 Misol:\n[Misol]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ AMALIYOT\n━━━━━━━━━━━━━━━━━━━━\n[Kichik topshiriq]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Eslab qoling:\n[Asosiy fikra]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "ru": {
        "welcome":         "👋 Добро пожаловать!\n\n🌍 Выберите язык:",
        "soha":            "✅ Язык выбран!\n\n📂 Выберите сферу:",
        "fan":             "📚 Выберите предмет:",
        "choose_topic":    "📌 Выберите тему:",
        "daraja":          "📊 Выберите уровень:",
        "maqsad":          "🎯 Какова ваша цель?",
        "vaqt":            "⏰ Сколько времени в день?",
        "loading":         "🤖 AI готовит урок...",
        "test_loading":    "🤖 Тест готовится...",
        "test_result":     "📊 Выберите уровень по результату теста:",
        "understood":      "✅ Понял",
        "not_understood":  "❓ Не понял",
        "ask":             "💬 Задать вопрос",
        "home":            "🏠 Главная",
        "pro":             "🏆 Стать профессионалом",
        "job":             "💼 Найти работу",
        "learn":           "📚 Получить знания",
        "project":         "🚀 Создать проект",
        "ask_prompt":      "✍️ Напишите ваш вопрос 👇",
        "lesson_done":     "🎉 Отлично! Урок завершён!\n\n⭐ День {kun} пройден!",
        "next_lesson":     "➡️ Урок {kun}-го дня 🔓",
        "next_post":       "➡️ Следующий пост",
        "next_day_locked": "🔒 Следующий урок откроется через 12 часов",
        "post_note":       "Это пост {current_post}/{total_posts}. Объясните эту часть с помощью одной картинки или диаграммы.",
        "post_understood": "✅ Я понял этот раздел. Нажмите следующий пост, чтобы продолжить.",
        "daraja_unknown":  "🤔 Не знаю свой уровень — пройти тест",
        "lang_name":       "Русский",
        "test_prompt":     "Напишите 5 вопросов с множественным выбором (A B C D) по '{fan}' для оценки уровня ученика. Ответьте на {lang_name}.",
        "answer_prompt":   "По теме '{fan}' вопрос: {question}. Объясните на {lang_name}.",
        "lesson_template": "Напишите урок на {lang_name} языке.\n\nУченик:\n- Предмет: {fan}\n- Уровень: {daraja}\n- Цель: {maqsad}\n- Время в день: {vaqt}\n{extra}\n\nИспользуйте ТОЧНЫЙ формат:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 День {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Тема сегодня: [ТЕМА]\n\n[Краткое введение]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 ОСНОВНАЯ КОНЦЕПЦИЯ\n━━━━━━━━━━━━━━━━━━━━\n[Объяснение]\n\n🔍 Пример:\n[Пример]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ ПРАКТИКА\n━━━━━━━━━━━━━━━━━━━━\n[Небольшое задание]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Запомните:\n[Ключевая идея]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "en": {
        "welcome":         "👋 Welcome!\n\n🌍 Choose your language:",
        "soha":            "✅ Language selected!\n\n📂 Choose a field:",
        "fan":             "📚 Choose a subject:",
        "choose_topic":    "📌 Choose a topic:",
        "daraja":          "📊 Choose your level:",
        "maqsad":          "🎯 What is your goal?",
        "vaqt":            "⏰ How much time per day?",
        "loading":         "🤖 AI is preparing your lesson...",
        "test_loading":    "🤖 Preparing test...",
        "test_result":     "📊 Choose your level based on test results:",
        "understood":      "✅ Understood",
        "not_understood":  "❓ Not understood",
        "ask":             "💬 Ask a question",
        "home":            "🏠 Home",
        "pro":             "🏆 Become professional",
        "job":             "💼 Find a job",
        "learn":           "📚 Gain knowledge",
        "project":         "🚀 Build a project",
        "ask_prompt":      "✍️ Write your question 👇",
        "lesson_done":     "🎉 Great! Lesson completed!\n\n⭐ Day {kun} done!",
        "next_lesson":     "➡️ Day {kun} lesson 🔓",
        "next_post":       "➡️ Next post",
        "next_day_locked": "🔒 Next lesson unlocks in 12 hours",
        "post_note":       "This is post {current_post}/{total_posts}. Use a single image or diagram to explain this part.",
        "post_understood": "✅ I understood this section. Tap next post to continue.",
        "daraja_unknown":  "🤔 I don't know my level — take a test",
        "lang_name":       "English",
        "test_prompt":     "Write 5 multiple choice questions (A B C D) about '{fan}' to assess student level. Write in {lang_name}.",
        "answer_prompt":   "Answer this question about '{fan}' in {lang_name} language. Be clear: {question}",
        "lesson_template": "Write a lesson in {lang_name} language.\n\nStudent:\n- Subject: {fan}\n- Level: {daraja}\n- Goal: {maqsad}\n- Daily time: {vaqt}\n{extra}\n\nUse this EXACT format:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 Day {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Today's topic: [TOPIC]\n\n[Brief introduction]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 KEY CONCEPT\n━━━━━━━━━━━━━━━━━━━━\n[Explanation]\n\n🔍 Example:\n[Example]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ PRACTICE\n━━━━━━━━━━━━━━━━━━━━\n[Small task]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Remember:\n[Key takeaway]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "de": {
        "welcome":         "👋 Willkommen!\n\n🌍 Sprache wählen:",
        "soha":            "✅ Sprache gewählt!\n\n📂 Bereich wählen:",
        "fan":             "📚 Fach wählen:",
        "daraja":          "📊 Niveau wählen:",
        "maqsad":          "🎯 Was ist Ihr Ziel?",
        "vaqt":            "⏰ Wie viel Zeit pro Tag?",
        "loading":         "🤖 KI bereitet die Lektion vor...",
        "test_loading":    "🤖 Test wird vorbereitet...",
        "test_result":     "📊 Niveau nach Testergebnis wählen:",
        "understood":      "✅ Verstanden",
        "not_understood":  "❓ Nicht verstanden",
        "ask":             "💬 Frage stellen",
        "home":            "🏠 Startseite",
        "pro":             "🏆 Profi werden",
        "job":             "💼 Arbeit finden",
        "learn":           "📚 Wissen erlangen",
        "project":         "🚀 Projekt erstellen",
        "ask_prompt":      "✍️ Schreiben Sie Ihre Frage 👇",
        "lesson_done":     "🎉 Toll! Lektion abgeschlossen!\n\n⭐ Tag {kun} erledigt!",
        "next_lesson":     "➡️ Tag {kun} Lektion 🔓",
        "next_post":       "➡️ Nächster Beitrag",
        "next_day_locked": "🔒 Nächste Lektion öffnet sich in 12 Stunden",
        "post_note":       "Dies ist Beitrag {current_post}/{total_posts}. Erklären Sie diesen Teil mit einem Bild oder Diagramm.",
        "post_understood": "✅ Ich habe diesen Abschnitt verstanden. Drücken Sie nächsten Beitrag, um fortzufahren.",
        "daraja_unknown":  "🤔 Niveau unbekannt — Test machen",
        "lang_name":       "Deutsch",
        "test_prompt":     "Schreiben Sie 5 Multiple-Choice-Fragen (A B C D) zu '{fan}' zur Bewertung. Antworten Sie auf {lang_name}.",
        "answer_prompt":   "Beantworten Sie diese Frage zu '{fan}' auf {lang_name}. Seien Sie klar: {question}",
        "lesson_template": "Schreiben Sie eine Lektion auf {lang_name}.\n\nSchüler:\n- Fach: {fan}\n- Niveau: {daraja}\n- Ziel: {maqsad}\n- Tägliche Zeit: {vaqt}\n{extra}\n\nVerwenden Sie dieses GENAUE Format:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 Tag {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Heutiges Thema: [THEMA]\n\n[Kurze Einführung]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 KERNKONZEPT\n━━━━━━━━━━━━━━━━━━━━\n[Erklärung]\n\n🔍 Beispiel:\n[Beispiel]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ ÜBUNG\n━━━━━━━━━━━━━━━━━━━━\n[Kleine Aufgabe]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Merken:\n[Wichtiger Punkt]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "fr": {
        "welcome":         "👋 Bienvenue!\n\n🌍 Choisissez votre langue:",
        "soha":            "✅ Langue choisie!\n\n📂 Choisissez un domaine:",
        "fan":             "📚 Choisissez une matière:",
        "daraja":          "📊 Choisissez votre niveau:",
        "maqsad":          "🎯 Quel est votre objectif?",
        "vaqt":            "⏰ Combien de temps par jour?",
        "loading":         "🤖 L'IA prépare la leçon...",
        "test_loading":    "🤖 Préparation du test...",
        "test_result":     "📊 Choisissez le niveau selon les résultats:",
        "understood":      "✅ Compris",
        "not_understood":  "❓ Pas compris",
        "ask":             "💬 Poser une question",
        "home":            "🏠 Accueil",
        "pro":             "🏆 Devenir professionnel",
        "job":             "💼 Trouver un emploi",
        "learn":           "📚 Acquérir des connaissances",
        "project":         "🚀 Créer un projet",
        "ask_prompt":      "✍️ Écrivez votre question 👇",
        "lesson_done":     "🎉 Excellent! Leçon terminée!\n\n⭐ Jour {kun} accompli!",
        "next_lesson":     "➡️ Leçon du jour {kun} 🔓",
        "next_post":       "➡️ Publication suivante",
        "next_day_locked": "🔒 La prochaine leçon s'ouvrira dans 12 heures",
        "post_note":       "Ceci est le post {current_post}/{total_posts}. Expliquez cette partie avec une image ou un diagramme.",
        "post_understood": "✅ J'ai compris cette partie. Appuyez sur la publication suivante pour continuer.",
        "daraja_unknown":  "🤔 Niveau inconnu — passer un test",
        "lang_name":       "Français",
        "test_prompt":     "Écrivez 5 questions à choix multiples (A B C D) sur '{fan}'. Écrivez en {lang_name}.",
        "answer_prompt":   "Répondez à cette question sur '{fan}' en {lang_name}. Soyez clair: {question}",
        "lesson_template": "Écrivez une leçon en {lang_name}.\n\nÉtudiant:\n- Matière: {fan}\n- Niveau: {daraja}\n- Objectif: {maqsad}\n- Temps quotidien: {vaqt}\n{extra}\n\nUtilisez ce format EXACT:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 Jour {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Sujet du jour: [SUJET]\n\n[Brève introduction]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 CONCEPT CLÉ\n━━━━━━━━━━━━━━━━━━━━\n[Explication]\n\n🔍 Exemple:\n[Exemple]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ PRATIQUE\n━━━━━━━━━━━━━━━━━━━━\n[Petite tâche]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Retenir:\n[Point clé]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "es": {
        "welcome":         "👋 ¡Bienvenido!\n\n🌍 Elige tu idioma:",
        "soha":            "✅ ¡Idioma elegido!\n\n📂 Elige un campo:",
        "fan":             "📚 Elige una materia:",
        "daraja":          "📊 Elige tu nivel:",
        "maqsad":          "🎯 ¿Cuál es tu objetivo?",
        "vaqt":            "⏰ ¿Cuánto tiempo por día?",
        "loading":         "🤖 La IA está preparando la lección...",
        "test_loading":    "🤖 Preparando el test...",
        "test_result":     "📊 Elige el nivel según los resultados:",
        "understood":      "✅ Entendido",
        "not_understood":  "❓ No entendido",
        "ask":             "💬 Hacer una pregunta",
        "home":            "🏠 Inicio",
        "pro":             "🏆 Ser profesional",
        "job":             "💼 Encontrar trabajo",
        "learn":           "📚 Adquirir conocimiento",
        "project":         "🚀 Crear un proyecto",
        "ask_prompt":      "✍️ Escribe tu pregunta 👇",
        "lesson_done":     "🎉 ¡Excelente! ¡Lección completada!\n\n⭐ ¡Día {kun} hecho!",
        "next_lesson":     "➡️ Lección del día {kun} 🔓",
        "next_post":       "➡️ Siguiente publicación",
        "next_day_locked": "🔒 La próxima lección se abrirá en 12 horas",
        "post_note":       "Este es el post {current_post}/{total_posts}. Explique esta parte con una sola imagen o diagrama.",
        "post_understood": "✅ Entendí esta parte. Presiona siguiente publicación para continuar.",
        "daraja_unknown":  "🤔 No sé mi nivel — hacer un test",
        "lang_name":       "Español",
        "test_prompt":     "Escribe 5 preguntas de opción múltiple (A B C D) sobre '{fan}'. Escribe en {lang_name}.",
        "answer_prompt":   "Responde esta pregunta sobre '{fan}' en {lang_name}. Sé claro: {question}",
        "lesson_template": "Escribe una lección en {lang_name}.\n\nEstudiante:\n- Materia: {fan}\n- Nivel: {daraja}\n- Objetivo: {maqsad}\n- Tiempo diario: {vaqt}\n{extra}\n\nUsa este formato EXACTO:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 Día {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Tema de hoy: [TEMA]\n\n[Breve introducción]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 CONCEPTO CLAVE\n━━━━━━━━━━━━━━━━━━━━\n[Explicación]\n\n🔍 Ejemplo:\n[Ejemplo]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ PRÁCTICA\n━━━━━━━━━━━━━━━━━━━━\n[Tarea pequeña]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Recuerda:\n[Punto clave]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "tr": {
        "welcome":         "👋 Hoş geldiniz!\n\n🌍 Dilinizi seçin:",
        "soha":            "✅ Dil seçildi!\n\n📂 Alan seçin:",
        "fan":             "📚 Konu seçin:",
        "daraja":          "📊 Seviyenizi seçin:",
        "maqsad":          "🎯 Hedefiniz nedir?",
        "vaqt":            "⏰ Günde ne kadar vakit?",
        "loading":         "🤖 AI ders hazırlıyor...",
        "test_loading":    "🤖 Test hazırlanıyor...",
        "test_result":     "📊 Test sonucuna göre seviye seçin:",
        "understood":      "✅ Anladım",
        "not_understood":  "❓ Anlamadım",
        "ask":             "💬 Soru sor",
        "home":            "🏠 Ana sayfa",
        "pro":             "🏆 Profesyonel ol",
        "job":             "💼 İş bul",
        "learn":           "📚 Bilgi edin",
        "project":         "🚀 Proje oluştur",
        "ask_prompt":      "✍️ Sorunuzu yazın 👇",
        "lesson_done":     "🎉 Harika! Ders tamamlandı!\n\n⭐ {kun}. gün bitti!",
        "next_lesson":     "➡️ {kun}. gün dersi 🔓",
        "next_post":       "➡️ Sonraki gönderi",
        "next_day_locked": "🔒 Bir sonraki ders 12 saat içinde açılacak",
        "post_note":       "Bu {current_post}/{total_posts} gönderi. Her bölümü bir resim veya diyagram ile açıklayın.",
        "post_understood": "✅ Bu bölümü anladım. Devam etmek için sonraki gönderiye basın.",
        "daraja_unknown":  "🤔 Seviyemi bilmiyorum — test al",
        "lang_name":       "Türkçe",
        "test_prompt":     "'{fan}' hakkında 5 tane çoktan seçmeli soru yazın (A B C D). {lang_name} dilinde yazın.",
        "answer_prompt":   "'{fan}' hakkında bu soruyu {lang_name} dilinde yanıtlayın. Açık olun: {question}",
        "lesson_template": "{lang_name} dilinde bir ders yazın.\n\nÖğrenci:\n- Konu: {fan}\n- Seviye: {daraja}\n- Hedef: {maqsad}\n- Günlük zaman: {vaqt}\n{extra}\n\nBu TAM OLARAK bu formatı kullanın:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 {kun}. gün\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 Bugünün konusu: [KONU]\n\n[Kısa giriş]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 ANA KAVRAM\n━━━━━━━━━━━━━━━━━━━━\n[Açıklama]\n\n🔍 Örnek:\n[Örnek]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ PRATIK\n━━━━━━━━━━━━━━━━━━━━\n[Küçük görev]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 Hatırla:\n[Önemli nokta]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "ar": {
        "welcome":         "👋 مرحباً!\n\n🌍 اختر لغتك:",
        "soha":            "✅ تم اختيار اللغة!\n\n📂 اختر مجالاً:",
        "fan":             "📚 اختر موضوعاً:",
        "choose_topic":    "📌 اختر التخصص:",
        "daraja":          "📊 اختر مستواك:",
        "maqsad":          "🎯 ما هدفك؟",
        "vaqt":            "⏰ كم من الوقت يومياً؟",
        "loading":         "🤖 الذكاء الاصطناعي يُعدّ الدرس...",
        "test_loading":    "🤖 جارٍ تحضير الاختبار...",
        "test_result":     "📊 اختر المستوى بناءً على نتيجة الاختبار:",
        "understood":      "✅ فهمت",
        "not_understood":  "❓ لم أفهم",
        "ask":             "💬 طرح سؤال",
        "home":            "🏠 الرئيسية",
        "pro":             "🏆 أصبح محترفاً",
        "job":             "💼 إيجاد عمل",
        "learn":           "📚 اكتساب المعرفة",
        "project":         "🚀 إنشاء مشروع",
        "ask_prompt":      "✍️ اكتب سؤالك 👇",
        "lesson_done":     "🎉 رائع! اكتمل الدرس!\n\n⭐ اليوم {kun} منجز!",
        "next_lesson":     "➡️ درس اليوم {kun} 🔓",
        "next_post":       "➡️ المنشور التالي",
        "next_day_locked": "🔒 الدرس التالي سيفتح خلال 12 ساعة",
        "post_note":       "هذا هو المنشور {current_post}/{total_posts}. اشرح هذا الجزء بصورة أو مخطط واحد.",
        "post_understood": "✅ فهمت هذا القسم. اضغط على المنشور التالي للمتابعة.",
        "daraja_unknown":  "🤔 لا أعرف مستواي — أجري اختباراً",
        "lang_name":       "العربية",
        "test_prompt":     "اكتب 5 أسئلة اختيار من متعدد (A B C D) عن '{fan}'. اكتب بـ {lang_name}.",
        "answer_prompt":   "أجب على هذا السؤال عن '{fan}' بـ {lang_name}. كن واضحاً: {question}",
        "lesson_template": "اكتب درساً بـ {lang_name}.\n\nالطالب:\n- الموضوع: {fan}\n- المستوى: {daraja}\n- الهدف: {maqsad}\n- الوقت اليومي: {vaqt}\n{extra}\n\nاستخدم هذا التنسيق تماماً:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 اليوم {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 موضوع اليوم: [الموضوع]\n\n[مقدمة موجزة]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 المفهوم الأساسي\n━━━━━━━━━━━━━━━━━━━━\n[شرح]\n\n🔍 مثال:\n[مثال]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ التطبيق\n━━━━━━━━━━━━━━━━━━━━\n[مهمة صغيرة]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 تذكر:\n[نقطة رئيسية]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "zh": {
        "welcome":         "👋 欢迎！\n\n🌍 请选择语言：",
        "soha":            "✅ 语言已选择！\n\n📂 请选择领域：",
        "fan":             "📚 请选择科目：",
        "choose_topic":    "📌 选择一个主题：",
        "daraja":          "📊 请选择您的级别：",
        "maqsad":          "🎯 您的目标是什么？",
        "vaqt":            "⏰ 每天学习多长时间？",
        "loading":         "🤖 AI正在准备课程...",
        "test_loading":    "🤖 正在准备测试...",
        "test_result":     "📊 根据测试结果选择级别：",
        "understood":      "✅ 明白了",
        "not_understood":  "❓ 不明白",
        "ask":             "💬 提问",
        "home":            "🏠 主页",
        "pro":             "🏆 成为专业人士",
        "job":             "💼 找工作",
        "learn":           "📚 获取知识",
        "project":         "🚀 创建项目",
        "ask_prompt":      "✍️ 请写下您的问题 👇",
        "lesson_done":     "🎉 太棒了！课程完成！\n\n⭐ 第{kun}天完成！",
        "next_lesson":     "➡️ 第{kun}天课程 🔓",
        "next_post":       "➡️ 下一条发布",
        "next_day_locked": "🔒 下一节课将在12小时后开启",
        "post_note":       "这是第 {current_post}/{total_posts} 条发布。请用一张图片或图表解释这一部分。",
        "post_understood": "✅ 我已经明白了这部分。点击下一条发布继续。",
        "daraja_unknown":  "🤔 不知道我的级别 — 参加测试",
        "lang_name":       "中文",
        "test_prompt":     "写5道关于'{fan}'的选择题（A B C D）。用{lang_name}写。",
        "answer_prompt":   "用{lang_name}回答这个关于'{fan}'的问题。要清楚：{question}",
        "lesson_template": "用{lang_name}写一节课。\n\n学生:\n- 科目: {fan}\n- 级别: {daraja}\n- 目标: {maqsad}\n- 每天学习时间: {vaqt}\n{extra}\n\n使用这个确切的格式:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 第{kun}天\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 今天的主题: [主题]\n\n[简短介绍]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 核心概念\n━━━━━━━━━━━━━━━━━━━━\n[解释]\n\n🔍 例子:\n[例子]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ 实践\n━━━━━━━━━━━━━━━━━━━━\n[小任务]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 记住:\n[关键要点]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "ja": {
        "welcome":         "👋 ようこそ！\n\n🌍 言語を選んでください：",
        "soha":            "✅ 言語が選択されました！\n\n📂 分野を選んでください：",
        "fan":             "📚 科目を選んでください：",
        "choose_topic":    "📌 トピックを選んでください：",
        "daraja":          "📊 レベルを選んでください：",
        "maqsad":          "🎯 目標は何ですか？",
        "vaqt":            "⏰ 1日何時間学習できますか？",
        "loading":         "🤖 AIがレッスンを準備中...",
        "test_loading":    "🤖 テストを準備中...",
        "test_result":     "📊 テスト結果に基づいてレベルを選んでください：",
        "understood":      "✅ わかりました",
        "not_understood":  "❓ わかりません",
        "ask":             "💬 質問する",
        "home":            "🏠 ホーム",
        "pro":             "🏆 プロになる",
        "job":             "💼 仕事を見つける",
        "learn":           "📚 知識を得る",
        "project":         "🚀 プロジェクトを作る",
        "ask_prompt":      "✍️ 質問を書いてください 👇",
        "lesson_done":     "🎉 素晴らしい！レッスン完了！\n\n⭐ {kun}日目達成！",
        "next_lesson":     "➡️ {kun}日目のレッスン 🔓",
        "next_post":       "➡️ 次の投稿",
        "next_day_locked": "🔒 次のレッスンは12時間後に開きます",
        "post_note":       "これは投稿 {current_post}/{total_posts} です。この部分を1つの画像または図で説明してください。",
        "post_understood": "✅ この部分を理解しました。次の投稿を押して続行してください。",
        "daraja_unknown":  "🤔 レベルがわからない — テストを受ける",
        "lang_name":       "日本語",
        "test_prompt":     "'{fan}'に関する5つの選択肢問題（A B C D）を書いてください。{lang_name}で書いてください。",
        "answer_prompt":   "'{fan}'に関するこの質問に{lang_name}で答えてください。明確にしてください：{question}",
        "lesson_template": "{lang_name}でレッスンを書いてください。\n\n学生:\n- 科目: {fan}\n- レベル: {daraja}\n- 目標: {maqsad}\n- 毎日の学習時間: {vaqt}\n{extra}\n\nこの正確な形式を使用してください:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 {kun}日目\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 今日のトピック: [トピック]\n\n[簡単な紹介]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 主要概念\n━━━━━━━━━━━━━━━━━━━━\n[説明]\n\n🔍 例:\n[例]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ 練習\n━━━━━━━━━━━━━━━━━━━━\n[小さなタスク]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 覚えておいてください:\n[重要なポイント]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "ko": {
        "welcome":         "👋 환영합니다!\n\n🌍 언어를 선택하세요:",
        "soha":            "✅ 언어가 선택되었습니다!\n\n📂 분야를 선택하세요:",
        "fan":             "📚 과목을 선택하세요:",
        "daraja":          "📊 레벨을 선택하세요:",
        "maqsad":          "🎯 목표가 무엇인가요?",
        "vaqt":            "⏰ 하루에 얼마나 공부할 수 있나요?",
        "loading":         "🤖 AI가 수업을 준비 중...",
        "test_loading":    "🤖 테스트 준비 중...",
        "test_result":     "📊 테스트 결과에 따라 레벨을 선택하세요:",
        "understood":      "✅ 이해했습니다",
        "not_understood":  "❓ 이해 못했습니다",
        "ask":             "💬 질문하기",
        "home":            "🏠 홈",
        "pro":             "🏆 전문가 되기",
        "job":             "💼 취업하기",
        "learn":           "📚 지식 얻기",
        "project":         "🚀 프로젝트 만들기",
        "ask_prompt":      "✍️ 질문을 입력하세요 👇",
        "lesson_done":     "🎉 훌륭해요! 수업 완료!\n\n⭐ {kun}일차 완료!",
        "next_lesson":     "➡️ {kun}일차 수업 🔓",
        "next_post":       "➡️ 다음 게시물",
        "next_day_locked": "🔒 다음 수업은 12시간 후에 열립니다",
        "post_note":       "이것은 {current_post}/{total_posts} 번째 게시물입니다. 이 부분을 하나의 이미지나 다이어그램으로 설명하세요.",
        "post_understood": "✅ 이 부분을 이해했습니다. 계속하려면 다음 게시물을 누르세요.",
        "daraja_unknown":  "🤔 레벨을 모르겠어요 — 테스트 받기",
        "lang_name":       "한국어",
        "test_prompt":     "'{fan}'에 대한 객관식 문제 5개(A B C D)를 작성하세요. {lang_name}로 작성하세요.",
        "answer_prompt":   "'{fan}'에 대한 이 질문에 {lang_name}로 답하세요. 명확하게 하세요: {question}",
        "lesson_template": "{lang_name}로 수업을 작성하세요.\n\n학생:\n- 과목: {fan}\n- 레벨: {daraja}\n- 목표: {maqsad}\n- 일일 학습 시간: {vaqt}\n{extra}\n\n이 정확한 형식을 사용하세요:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 {kun}일차\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 오늘의 주제: [주제]\n\n[짧은 소개]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 핵심 개념\n━━━━━━━━━━━━━━━━━━━━\n[설명]\n\n🔍 예시:\n[예시]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ 연습\n━━━━━━━━━━━━━━━━━━━━\n[작은 과제]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 기억하세요:\n[핵심 내용]\n━━━━━━━━━━━━━━━━━━━━",
    },
    "hi": {
        "welcome":         "👋 स्वागत है!\n\n🌍 अपनी भाषा चुनें:",
        "soha":            "✅ भाषा चुनी गई!\n\n📂 क्षेत्र चुनें:",
        "fan":             "📚 विषय चुनें:",
        "daraja":          "📊 अपना स्तर चुनें:",
        "maqsad":          "🎯 आपका लक्ष्य क्या है?",
        "vaqt":            "⏰ प्रतिदिन कितना समय?",
        "loading":         "🤖 AI पाठ तैयार कर रहा है...",
        "test_loading":    "🤖 परीक्षण तैयार हो रहा है...",
        "test_result":     "📊 परीक्षण परिणाम के अनुसार स्तर चुनें:",
        "understood":      "✅ समझ गया",
        "not_understood":  "❓ समझ नहीं आया",
        "ask":             "💬 प्रश्न पूछें",
        "home":            "🏠 होम",
        "pro":             "🏆 पेशेवर बनें",
        "job":             "💼 नौकरी खोजें",
        "learn":           "📚 ज्ञान प्राप्त करें",
        "project":         "🚀 प्रोजेक्ट बनाएं",
        "ask_prompt":      "✍️ अपना प्रश्न लिखें 👇",
        "lesson_done":     "🎉 शानदार! पाठ पूरा हुआ!\n\n⭐ दिन {kun} पूरा!",
        "next_lesson":     "➡️ दिन {kun} का पाठ 🔓",
        "next_post":       "➡️ अगला पोस्ट",
        "next_day_locked": "🔒 अगला पाठ 12 घंटे बाद खुलेगा",
        "post_note":       "यह पोस्ट {current_post}/{total_posts} है। इस भाग को एक चित्र या आरेख के साथ समझाइए।",
        "post_understood": "✅ मैंने इस भाग को समझ लिया है। जारी रखने के लिए अगला पोस्ट दबाएँ।",
        "daraja_unknown":  "🤔 स्तर नहीं जानता — परीक्षण लें",
        "lang_name":       "हिंदी",
        "test_prompt":     "'{fan}' के बारे में 5 बहुविकल्पीय प्रश्न (A B C D) लिखें। {lang_name} में लिखें।",
        "answer_prompt":   "'{fan}' के बारे में इस प्रश्न का उत्तर {lang_name} में दें। स्पष्ट हो: {question}",
        "lesson_template": "{lang_name} में एक पाठ लिखें।\n\nछात्र:\n- विषय: {fan}\n- स्तर: {daraja}\n- लक्ष्य: {maqsad}\n- दैनिक समय: {vaqt}\n{extra}\n\nइस सटीक प्रारूप का उपयोग करें:\n\n━━━━━━━━━━━━━━━━━━━━\n📖 {fan} | 📅 दिन {kun}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 आज का विषय: [विषय]\n\n[संक्षिप्त परिचय]\n\n━━━━━━━━━━━━━━━━━━━━\n💡 मुख्य अवधारणा\n━━━━━━━━━━━━━━━━━━━━\n[व्याख्या]\n\n🔍 उदाहरण:\n[उदाहरण]\n\n━━━━━━━━━━━━━━━━━━━━\n✏️ अभ्यास\n━━━━━━━━━━━━━━━━━━━━\n[छोटा कार्य]\n\n━━━━━━━━━━━━━━━━━━━━\n🧠 याद रखें:\n[मुख्य बात]\n━━━━━━━━━━━━━━━━━━━━",
    },
}

def get_text(lang, key, **kwargs):
    """Tanlangan tilda matn qaytaradi"""
    texts = TEXTS.get(lang, TEXTS['uz'])
    text = texts.get(key, TEXTS['uz'].get(key, key))
    if kwargs:
        text = text.format(**kwargs)
    return text

def get_lang_name(lang):
    """Til nomini qaytaradi"""
    return TEXTS.get(lang, TEXTS['uz'])['lang_name']

# Har bir tildagi menyu sohalar
FIELDS_BY_LANG = {
    "uz": {
        "💻 IT":                [["🐍 Dasturlash", "🌐 Veb dasturlash"], ["📊 Data Science", "🛡️ Kiberhavfsizlik"], ["📱 Mobile", "🤖 Sun'iy intellekt"], ["🎮 Game Dev", "☁️ Cloud computing"]],
        "🏥 Tibbiyot":          [["🫀 Anatomiya", "💊 Farmakologiya"], ["🧬 Biologiya", "🏥 Klinik tibbiyot"], ["🧪 Kimyo", "🧠 Nevrologiya"]],
        "⚖️ Huquq":             [["📜 Fuqarolik huquqi", "🏛️ Jinoyat huquqi"], ["💼 Biznes huquqi", "🌍 Xalqaro huquq"], ["👨‍👩‍👧 Oila huquqi", "⚖️ Konstitutsiya"]],
        "📈 Biznes":            [["📊 Marketing", "💰 Moliyaviy boshqaruv"], ["🤝 Menedjment", "📦 Logistika"], ["🚀 Startup", "📣 SMM"]],
        "🔬 Fan":               [["⚛️ Fizika", "🧪 Kimyo"], ["🧬 Biologiya", "🌍 Geografiya"], ["🔭 Astronomiya", "🧮 Matematika"]],
        "🎨 Dizayn":            [["🖥️ UI/UX", "🎨 Grafik dizayn"], ["🏠 Interior dizayn", "👗 Moda dizayn"], ["📸 Fotografiya", "🎬 Motion dizayn"]],
        "🌍 Tillar":            [["🇬🇧 Ingliz tili", "🇷🇺 Rus tili"], ["🇩🇪 Nemis tili", "🇫🇷 Frantsuz tili"], ["🇨🇳 Xitoy tili", "🇯🇵 Yapon tili"], ["🇰🇷 Koreys tili", "🇸🇦 Arab tili"]],
        "🏫 Maktab":            [["➗ Matematika", "⚛️ Fizika"], ["📖 Ona tili", "📚 Adabiyot"], ["📜 Tarix", "🌍 Geografiya"], ["🧪 Kimyo", "🧬 Biologiya"], ["💻 Informatika", "🇬🇧 Ingliz tili"]],
        "🏗️ Muhandislik":       [["⚡ Elektrotexnika", "🔧 Mexanika"], ["🏗️ Qurilish", "🛢️ Neft va gaz"], ["🤖 Robototexnika", "✈️ Aviatsiya"]],
        "🌱 Qishloq xo'jaligi": [["🌾 Agronomiya", "🐄 Chorvachilik"], ["🌿 Botanika", "🚜 Texnika"], ["💧 Irrigatsiya"]],
        "🎵 Musiqa":            [["🎹 Pianino", "🎸 Gitara"], ["🎤 Vokal", "🥁 Baraban"], ["🎼 Musiqa nazariyasi"]],
        "🍳 Oshpazlik":         [["🍕 Yevropa taomlari", "🍜 Osiyo taomlari"], ["🥗 Sog'lom ovqat", "🎂 Konditерlik"], ["🍳 Asosiy taomlar"]],
        "✈️ Turizm":            [["🗺️ Tur operatorlik", "🏨 Mehmonxona biznesi"], ["🌍 Geografiya", "🗣️ Gid bo'lish"], ["✈️ Aviatsiya asoslari"]],
        "💰 Moliya":            [["📈 Investitsiya", "💳 Bank ishi"], ["📊 Buxgalteriya", "🪙 Kriptovalyuta"], ["💱 Valyuta bozori"]],
        "🧠 Psixologiya":       [["🧠 Umumiy psixologiya", "👨‍👩‍👧 Oila psixologiyasi"], ["💼 Biznes psixologiyasi", "🧒 Bolalar psixologiyasi"], ["😔 Klinik psixologiya"]],
        "🏋️ Sport":             [["💪 Fitness", "⚽ Futbol"], ["🥊 Jang san'atlari", "🏊 Suzish"], ["🧘 Yoga"]],
        "🎬 Kinematografiya":   [["🎬 Rejissura", "🎥 Operator ishi"], ["✂️ Montaj", "🎭 Aktyorlik"], ["🎵 Ovoz rejissurasi"]],
        "🔧 Avtomexanika":      [["🔧 Dvigatel", "⚡ Elektr tizimi"], ["🛞 Xodovaya", "🎨 Kuzov ishi"], ["🔩 Diagnostika"]],
        "📡 Jurnalistika":      [["📰 Gazeta", "📺 TV jurnalistika"], ["📱 SMM va blog", "📡 Radio"], ["📸 Fotojurnalistika"]],
        "📸 Fotografiya":       [["📷 Asoslar", "💡 Yorug'lik"], ["🎨 Kompozitsiya", "🖥️ Fotoshop"], ["📸 Portrait"]],
    },
    "en": {
        "💻 IT": [["🐍 Programming", "🌐 Web Development"], ["📊 Data Science", "🛡️ Cybersecurity"], ["📱 Mobile", "🤖 Artificial Intelligence"], ["🎮 Game Dev", "☁️ Cloud Computing"]],
        "🏥 Medicine": [["🫀 Anatomy", "💊 Pharmacology"], ["🧬 Biology", "🏥 Clinical Medicine"], ["🧪 Chemistry", "🧠 Neurology"]],
        "⚖️ Law": [["📜 Civil Law", "🏛️ Criminal Law"], ["💼 Business Law", "🌍 International Law"], ["👨‍👩‍👧 Family Law", "⚖️ Constitutional Law"]],
        "📈 Business": [["📊 Marketing", "💰 Financial Management"], ["🤝 Management", "📦 Logistics"], ["🚀 Startup", "📣 Social Media"]],
        "🔬 Science": [["⚛️ Physics", "🧪 Chemistry"], ["🧬 Biology", "🌍 Geography"], ["🔭 Astronomy", "🧮 Mathematics"]],
        "🎨 Design": [["🖥️ UI/UX", "🎨 Graphic Design"], ["🏠 Interior Design", "👗 Fashion Design"], ["📸 Photography", "🎬 Motion Design"]],
        "🌍 Languages": [["🇬🇧 English", "🇷🇺 Russian"], ["🇩🇪 German", "🇫🇷 French"], ["🇨🇳 Chinese", "🇯🇵 Japanese"], ["🇰🇷 Korean", "🇸🇦 Arabic"]],
        "🏫 School": [["➗ Mathematics", "⚛️ Physics"], ["📖 Literature", "📚 Books"], ["📜 History", "🌍 Geography"], ["🧪 Chemistry", "🧬 Biology"], ["💻 Computer Science", "🇬🇧 English"]],
        "🏗️ Engineering": [["⚡ Electrical Engineering", "🔧 Mechanics"], ["🏗️ Construction", "🛢️ Oil and Gas"], ["🤖 Robotics", "✈️ Aviation"]],
        "🌱 Agriculture": [["🌾 Agronomy", "🐄 Livestock"], ["🌿 Botany", "🚜 Machinery"], ["💧 Irrigation"]],
        "🎵 Music": [["🎹 Piano", "🎸 Guitar"], ["🎤 Vocals", "🥁 Drums"], ["🎼 Music Theory"]],
        "🍳 Cooking": [["🍕 European Food", "🍜 Asian Cuisine"], ["🥗 Healthy Eating", "🎂 Pastry"], ["🍳 Basic Recipes"]],
        "✈️ Tourism": [["🗺️ Tour Operating", "🏨 Hotel Business"], ["🌍 Geography", "🗣️ Tour Guide"], ["✈️ Aviation Basics"]],
        "💰 Finance": [["📈 Investment", "💳 Banking"], ["📊 Accounting", "🪙 Cryptocurrency"], ["💱 Foreign Exchange"]],
        "🧠 Psychology": [["🧠 General Psychology", "👨‍👩‍👧 Family Psychology"], ["💼 Business Psychology", "🧒 Child Psychology"], ["😔 Clinical Psychology"]],
        "🏋️ Sports": [["💪 Fitness", "⚽ Football"], ["🥊 Martial Arts", "🏊 Swimming"], ["🧘 Yoga"]],
        "🎬 Cinema": [["🎬 Directing", "🎥 Cinematography"], ["✂️ Editing", "🎭 Acting"], ["🎵 Sound Design"]],
        "🔧 Auto Mechanics": [["🔧 Engine", "⚡ Electrical System"], ["🛞 Chassis", "🎨 Body Work"], ["🔩 Diagnostics"]],
        "📡 Journalism": [["📰 Newspaper", "📺 TV Journalism"], ["📱 Social Media & Blogs", "📡 Radio"], ["📸 Photo Journalism"]],
        "📸 Photography": [["📷 Basics", "💡 Lighting"], ["🎨 Composition", "🖥️ Photoshop"], ["📸 Portrait"]],
    }
}

def get_fields(lang):
    """Tanlangan tilga qarab sohalarni qaytaradi"""
    return FIELDS_BY_LANG.get(lang, FIELDS_BY_LANG['uz'])

def get_subfields(lang, subject):
    """Tanlangan mavzu uchun keyingi darajadagi subsohalarni qaytaradi"""
    return SUBFIELDS_BY_LANG.get(lang, {}).get(subject)

# Shuningdek, ba'zi sohalar uchun keyingi darajadagi mavzular
SUBFIELDS_BY_LANG = {
    "uz": {
        "🐍 Dasturlash": [["Python", "JavaScript"], ["C++", "Java"], ["Go", "Rust"], ["Kotlin", "Swift"]],
        "🌐 Veb dasturlash": [["Frontend", "Backend"], ["Full-stack", "Web Security"]],
        "📊 Data Science": [["Python", "R"], ["SQL", "MATLAB"]],
        "🤖 Sun'iy intellekt": [["Machine Learning", "Deep Learning"], ["NLP", "Computer Vision"]],
    },
    "en": {
        "🐍 Programming": [["Python", "JavaScript"], ["C++", "Java"], ["Go", "Rust"], ["Kotlin", "Swift"]],
        "🌐 Web Development": [["Frontend", "Backend"], ["Full-stack", "Web Security"]],
        "📊 Data Science": [["Python", "R"], ["SQL", "MATLAB"]],
        "🤖 Artificial Intelligence": [["Machine Learning", "Deep Learning"], ["NLP", "Computer Vision"]],
    },
}

# Har bir tildagi vaqt variantlari
VAQT_OPTIONS_BY_LANG = {
    "uz": ["⚡ 15 daqiqa", "📖 30 daqiqa", "💪 1 soat", "🔥 2 soat+"],
    "ru": ["⚡ 15 минут", "📖 30 минут", "💪 1 час", "🔥 2+ часа"],
    "en": ["⚡ 15 minutes", "📖 30 minutes", "💪 1 hour", "🔥 2+ hours"],
    "de": ["⚡ 15 Minuten", "📖 30 Minuten", "💪 1 Stunde", "🔥 2+ Stunden"],
    "fr": ["⚡ 15 minutes", "📖 30 minutes", "💪 1 heure", "🔥 2+ heures"],
    "es": ["⚡ 15 minutos", "📖 30 minutos", "💪 1 hora", "🔥 2+ horas"],
    "tr": ["⚡ 15 dakika", "📖 30 dakika", "💪 1 saat", "🔥 2+ saat"],
    "ar": ["⚡ 15 دقيقة", "📖 30 دقيقة", "💪 1 ساعة", "🔥 2+ ساعة"],
    "zh": ["⚡ 15分钟", "📖 30分钟", "💪 1小时", "🔥 2+小时"],
    "ja": ["⚡ 15分", "📖 30分", "💪 1時間", "🔥 2+時間"],
    "ko": ["⚡ 15분", "📖 30분", "💪 1시간", "🔥 2+시간"],
    "hi": ["⚡ 15 मिनट", "📖 30 मिनट", "💪 1 घंटा", "🔥 2+ घंटे"],
}
     
def get_vaqt_options(lang):
    """Tanlangan tilga qarab vaqt variantlarni qaytaradi"""
    return VAQT_OPTIONS_BY_LANG.get(lang, VAQT_OPTIONS_BY_LANG['uz'])

# Har bir tildagi daraja tugmalari
LEVELS_BY_LANG = {
    "uz": ["🟢 Boshlang'ich", "🟡 O'rta", "🔴 Yuqori"],
    "ru": ["🟢 Начальный", "🟡 Средний", "🔴 Высокий"],
    "en": ["🟢 Beginner", "🟡 Intermediate", "🔴 Advanced"],
    "de": ["🟢 Anfänger", "🟡 Mittel", "🔴 Fortgeschritten"],
    "fr": ["🟢 Débutant", "🟡 Intermédiaire", "🔴 Avancé"],
    "es": ["🟢 Principiante", "🟡 Intermedio", "🔴 Avanzado"],
    "tr": ["🟢 Başlangıç", "🟡 Orta", "🔴 İleri"],
    "ar": ["🟢 مبتدئ", "🟡 متوسط", "🔴 متقدم"],
    "zh": ["🟢 初级", "🟡 中级", "🔴 高级"],
    "ja": ["🟢 初心者", "🟡 中級", "🔴 上級"],
    "ko": ["🟢 초급", "🟡 중급", "🔴 고급"],
    "hi": ["🟢 शुरुआती", "🟡 मध्यम", "🔴 उन्नत"],
}

def get_levels(lang):
    """Tanlangan tilga qarab daraja tugmalarini qaytaradi"""
    return LEVELS_BY_LANG.get(lang, LEVELS_BY_LANG['uz'])